
kind: pipeline
name: java8

platform:
  arch: amd64

steps:
- name: prepare-dependencies
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-dl-java maven/org.json:json:20211205
  - artifact-dl-java omz/org.omegazero.common:common:latest

- name: prepare-source
  image: omz-ci-tools
  pull: never
  commands:
  - setversion src/org/omegazero/net/common/NetCommon.java

- name: build
  # use ECJ because of bug in default JDK 8 compiler (JDK-8139836)
  # use older version of ECJ with JDK 8 because of method signature changes in ByteBuffer in newer versions
  image: openjdk-ecj:4.14
  pull: never
  commands:
  - mkdir bin
  - ecj -verbose -d bin -cp json-20211205.jar:common-latest.jar -8 src
  - jar cf build.jar -C bin .
  depends_on:
  - prepare-dependencies
  - prepare-source

- name: publish
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-push-java build.jar omz/org.omegazero.net:netlib
  depends_on:
  - build
  environment:
    OMZ_ARTIFACT_PUSH_TOKEN:
      from_secret: artifact_push_token
