
name: ci
on: [push]

jobs:
  autobuild:
    runs-on: ubuntu-latest
    container:
      image: sw-vc.warpcs.org/omegazero/java-build
    steps:
      - uses: actions/checkout@v5
      - name: prepare
        run: |
          artifact-dl-java omz/org.omegazero.common:omz-common:latest
          mkdir build
          setversion net-common/main/java/org/omegazero/net/common/NetCommon.java
          curl -G "https://warpcs.org/site/software/r/license_bin_full.php" --data-urlencode "srcurl=${{ gitea.server_url }}/${{ gitea.repository }}/src/commit/${{ gitea.sha }}" > LICENSE_BIN
      - name: build-common
        run: |
          mkdir -p build/common/bin/META-INF
          cp LICENSE_BIN build/common/bin/META-INF/LICENSE
          ecj -verbose -d build/common/bin -cp omz-common-latest.jar -8 net-common/main/java
          jar cf build-common.jar -C build/common/bin .
      - name: build-nio-common
        run: |
          mkdir -p build/nio-common/bin/META-INF
          cp LICENSE_BIN build/nio-common/bin/META-INF/LICENSE
          ecj -verbose -d build/nio-common/bin -cp omz-common-latest.jar:build-common.jar -8 nio-common/main/java
          jar cf build-nio-common.jar -C build/nio-common/bin .
      - name: build-nio-client
        run: |
          mkdir -p build/nio-client/bin/META-INF
          cp LICENSE_BIN build/nio-client/bin/META-INF/LICENSE
          ecj -verbose -d build/nio-client/bin -cp omz-common-latest.jar:build-common.jar:build-nio-common.jar -8 nio-client/main/java
          jar cf build-nio-client.jar -C build/nio-client/bin .
      - name: build-nio-server
        run: |
          mkdir -p build/nio-server/bin/META-INF
          cp LICENSE_BIN build/nio-server/bin/META-INF/LICENSE
          ecj -verbose -d build/nio-server/bin -cp omz-common-latest.jar:build-common.jar:build-nio-common.jar -8 nio-server/main/java
          jar cf build-nio-server.jar -C build/nio-server/bin .
      - name: build-nio-all
        run: |
          mkdir -p build/nio-all/bin/META-INF
          cp -r build/common/bin/* build/nio-common/bin/* build/nio-client/bin/* build/nio-server/bin/* build/nio-all/bin
          cp LICENSE_BIN build/nio-all/bin/META-INF/LICENSE
          jar cf build-nio-all.jar -C build/nio-all/bin .
      - name: publish
        run: |
          artifact-push-java build-common.jar omz/org.omegazero.net:omz-netlib-common
          artifact-push-java build-nio-common.jar omz/org.omegazero.net:omz-netlib-nio-common
          artifact-push-java build-nio-client.jar omz/org.omegazero.net:omz-netlib-nio-client
          artifact-push-java build-nio-server.jar omz/org.omegazero.net:omz-netlib-nio-server
          artifact-push-java build-nio-all.jar omz/org.omegazero.net:omz-netlib-nio
    env:
      OMZ_ARTIFACT_PUSH_TOKEN: ${{ secrets.ARTIFACT_PUSH_TOKEN }}
